import { useTheme } from '@mui/material/styles'
import Head from 'next/head'
import Image from 'next/image'
import { FamilyTreeViewArea } from '../features/family-tree'
import { BaseLayout } from '../features/common/layouts'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <FamilyTreeViewArea />
      </BaseLayout>
    </>
  )
}
